name: "CI (Integração Continua): Primeira Action"

on: 
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # Ativa esse fluxo de trabalho para cada push ou pull que acontecer apontando para a branch master
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Definindo o que queremos executar
jobs:
    exemplo:  # Job: exemplo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            # Runs a single command using the runners shell
            - name: Run a one-line script
              run: echo Hello, world!
